services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    env_file:
      - .env
    ports:
      - "4566:4566"
    volumes:
      - "./.localstack:/var/lib/localstack"
    networks:
      - sky-comm

  postgres:
    image: postgres:16
    container_name: postgres
    env_file:
      - .env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - sky-comm

  redis:
    image: redis:7-alpine
    container_name: redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - sky-comm

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: terminal-service-app
    command: >
      bash -lc "uvicorn main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      localstack:
        condition: service_started
      redis:
        condition: service_healthy
    networks:
      - sky-comm

networks:
  sky-comm:
    external: true
