 app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: terminal-service-app
    command: >
      bash -lc "uvicorn terminal_service.main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      localstack:
        condition: service_healthy

