"""add device_id to messages

Revision ID: ab1ee6deab87
Revises: 8ae2dac54043
Create Date: 2025-09-03 14:23:32.745421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab1ee6deab87'
down_revision: Union[str, Sequence[str], None] = '8ae2dac54043'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('device_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_messages_device_id'), 'messages', ['device_id'], unique=False)
    op.create_foreign_key(None, 'messages', 'devices', ['device_id'], ['device_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_index(op.f('ix_messages_device_id'), table_name='messages')
    op.drop_column('messages', 'device_id')
    # ### end Alembic commands ###
