server:
  http_listen_port: 9080

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    pipeline_stages:
      - docker: {}
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: container
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: compose_service
      - source_labels: ['__meta_docker_container_label_service']
        target_label: service
      - source_labels: ['__meta_docker_container_label_env']
        target_label: env
      - target_label: job
        replacement: docker

  - job_name: systemd-journal
    journal:
        max_age: 12h
        labels:
          job: system
    relabel_configs:
        - source_labels: [ '__journal__systemd_unit' ]
          target_label: unit